### PR TITLE
Added a JSDOC Parser Test Using Chai & Mocha

### PR DESCRIPTION
**Pull request by Pika1998**

### CODE REVIEW

**Comment by rahil1304** [comment]
parserTest.js is the file that adds the test right? @Pika1998

**Comment by Pika1998** [comment]
@rahil1304 correct

**Comment by rahil1304** [comment]
Seems good to me. The only thing I would suggest is maybe choosing a better name for 'test-repository.' The name is a little misleading. Maybe something like output-test-files or test-output, etc would be a better naming convention. @Pika1998

**Comment by Pika1998** [comment]
Thanks @rahil1304 , test_output seems good to me, I will change it to that

**Pull request merged**
