### PR TITLE
bug fix #12

### LINKED ISSUE #12: Cannot find module @actions/exec
**Description**
Error occurs when `npm run dev` is run

**To Reproduce**
1. Go to 'express-autodocs'
2. `npm install`
3. `npm run dev`
4. `Error:  Cannot find module 'express-autodocs\node_modules\@actions\exec\lib\exec.js'. Please verify that the package.json has a valid "main" entry`

**Expected behavior**
Docs should be generated in output folder

**Screenshots**

**Desktop:**
 - OS: Windows 10

**Additional context**
The error is caused due to first line in [helpers/templateHelpers/createDocs.js](https://github.com/Pika1998/express-autodocs/blob/master/helpers/templateHelpers/createDocs.js) which isn't used anyway

The error is solved by removing this line

### PR DESCRIPTION
**Pull request by KulkarniSuraj**
removed unnecessary code in createDocs.js

### CODE REVIEW

**Review by Pika1998 — CHANGES_REQUESTED** [review]
Also, I don't think we will be needing `@actions/exec` in the **package.json file**
can you remove it using `npm remove @actions/exec` and test if it still runs

If it does, add that commit to this PR as well 😇

**Comment by KulkarniSuraj** [comment]
> Also, I don't think we will be needing `@actions/exec` in the **package.json file**
> can you remove it using `npm remove @actions/exec` and test if it still runs
> 
> If it does, add that commit to this PR as well 😇

The code works fine without that package
I saw that it isn't used anywhere in the code but I was not sure

**Review by Pika1998 — APPROVED** [review]
Great Job💖
Thank you

**Comment by Pika1998** [comment]
@all-contributors please add @KulkarniSuraj  for code test bugs

**Pull request merged**
