### PR TITLE
Serve Output Folder

### PR DESCRIPTION
**Pull request by rosborne132**
## Proposed changes

This PR serves the output HTML when running `npm run dev`
Linked issue: https://github.com/Pika1998/express-autodocs/issues/21

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](https://github.com/Pika1998/express-autodocs/docs/CONTRIBUTING.md) doc
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Labels

- hacktoberfest
- enchancement

## Further comments

- Pull down changes, run `npm run dev` and view HTML in localhost.

### CODE REVIEW

**Comment by Pika1998** [comment]
@rosborne132 can you please explain about the `dist` folder, I was thinking that we can directly serve the output generated in `test_repository/output`, I didn't quite get the dist part.

**Comment by rosborne132** [comment]
@Pika1998 I change to `test_repository/output`. I thought we were using the `dist` folder. :)

**Comment by Pika1998** [comment]
> @Pika1998 I change to `test_repository/output`. I thought we were using the `dist` folder. :)

Can you please also remove the changes like delete the `dist` folder and remove the packages installed related to it ?

**Comment by Pika1998** [comment]
> > @Pika1998 I change to `test_repository/output`. I thought we were using the `dist` folder. :)
> 
> Can you please also remove the changes like delete the `dist` folder and remove the packages installed related to it ?

@rosborne132 don't worry about this, I'll do that. It's my bad that I pushed some code which we are not using

**Review by Pika1998 — APPROVED** [review]
Great, thank you!💖

**Pull request merged**
